# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\app\widget\ui\account_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(702, 493)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_main = QtWidgets.QFrame(Dialog)
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_title = QtWidgets.QFrame(self.frame_main)
        self.frame_title.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_title.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_title.setObjectName("frame_title")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_title)
        self.horizontalLayout_2.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_title)
        self.pushButton_2.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/icon/coffee.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.label = QtWidgets.QLabel(self.frame_title)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.close_account = QtWidgets.QPushButton(self.frame_title)
        self.close_account.setMinimumSize(QtCore.QSize(30, 30))
        self.close_account.setMaximumSize(QtCore.QSize(30, 30))
        self.close_account.setText("")
        self.close_account.setObjectName("close_account")
        self.horizontalLayout_2.addWidget(self.close_account)
        self.verticalLayout_2.addWidget(self.frame_title)
        self.frame = QtWidgets.QFrame(self.frame_main)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(10, 10, 10, 15)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setSpacing(10)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setHorizontalSpacing(10)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMaximumSize(QtCore.QSize(55, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border:none;")
        self.label_2.setObjectName("label_2")
        self.gridLayout_11.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border:none;")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_11.addWidget(self.label_3, 0, 3, 1, 1)
        self.pushButton_newfile = QtWidgets.QPushButton(self.frame)
        self.pushButton_newfile.setMinimumSize(QtCore.QSize(150, 35))
        self.pushButton_newfile.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_newfile.setFont(font)
        self.pushButton_newfile.setStyleSheet("QPushButton {\n"
"    \n"
"    border-radius: 5px;    \n"
"    color : rgb(255,255,255);\n"
"    \n"
"    background-color: rgb(75, 104, 133);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"    padding-right:3px;\n"
"}")
        self.pushButton_newfile.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_newfile.setObjectName("pushButton_newfile")
        self.gridLayout_11.addWidget(self.pushButton_newfile, 0, 5, 1, 1)
        self.comboBox_file = QtWidgets.QComboBox(self.frame)
        self.comboBox_file.setMinimumSize(QtCore.QSize(210, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.comboBox_file.setFont(font)
        self.comboBox_file.setAutoFillBackground(False)
        self.comboBox_file.setStyleSheet("")
        self.comboBox_file.setIconSize(QtCore.QSize(16, 16))
        self.comboBox_file.setFrame(True)
        self.comboBox_file.setObjectName("comboBox_file")
        self.gridLayout_11.addWidget(self.comboBox_file, 0, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setMinimumSize(QtCore.QSize(125, 35))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_11.addWidget(self.comboBox, 0, 4, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_11, 1, 0, 1, 1)
        self.plainTextEdit_acc = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit_acc.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit_acc.setFont(font)
        self.plainTextEdit_acc.setStyleSheet("")
        self.plainTextEdit_acc.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plainTextEdit_acc.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plainTextEdit_acc.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plainTextEdit_acc.setObjectName("plainTextEdit_acc")
        self.gridLayout_10.addWidget(self.plainTextEdit_acc, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_10)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setSpacing(10)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.pushButton_close = QtWidgets.QPushButton(self.frame)
        self.pushButton_close.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_close.setMaximumSize(QtCore.QSize(150, 300))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_close.setFont(font)
        self.pushButton_close.setStyleSheet("QPushButton {\n"
"    \n"
"    border-radius: 5px;    \n"
"    color : rgb(255,255,255);\n"
"    \n"
"    background-color: rgb(75, 104, 133);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"    padding-right:3px;\n"
"}")
        self.pushButton_close.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_close.setObjectName("pushButton_close")
        self.gridLayout_12.addWidget(self.pushButton_close, 0, 2, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("border : none")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_12.addWidget(self.frame_4, 0, 0, 1, 1)
        self.pushButton_save = QtWidgets.QPushButton(self.frame)
        self.pushButton_save.setMinimumSize(QtCore.QSize(150, 35))
        self.pushButton_save.setMaximumSize(QtCore.QSize(150, 300))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setStyleSheet("QPushButton {\n"
"    \n"
"    border-radius: 5px;    \n"
"    color : rgb(255,255,255);\n"
"    \n"
"    background-color: rgb(75, 104, 133);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"    padding-right:3px;\n"
"}")
        self.pushButton_save.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout_12.addWidget(self.pushButton_save, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_12)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout_3.addWidget(self.frame_main)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Nhập tài khoản"))
        self.label.setText(_translate("Dialog", "Nhập tài khoản"))
        self.label_2.setText(_translate("Dialog", "Chọn File"))
        self.label_3.setText(_translate("Dialog", "Định dạng"))
        self.pushButton_newfile.setText(_translate("Dialog", "Tạo file"))
        self.pushButton_newfile.setShortcut(_translate("Dialog", "Ctrl+E"))
        self.comboBox.setItemText(0, _translate("Dialog", "Cookie"))
        self.comboBox.setItemText(1, _translate("Dialog", "Uid|pass|2fa|cookie"))
        self.plainTextEdit_acc.setPlaceholderText(_translate("Dialog", "Nhập tài khoản...."))
        self.pushButton_close.setText(_translate("Dialog", "Đóng cửa sổ"))
        self.pushButton_save.setText(_translate("Dialog", "Lưu dữ liệu"))
        self.pushButton_save.setShortcut(_translate("Dialog", "Ctrl+T"))
import files_rc
