# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\app\widget\ui\file_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(330, 158)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_main = QtWidgets.QFrame(Dialog)
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_title = QtWidgets.QFrame(self.frame_main)
        self.frame_title.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_title.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_title.setObjectName("frame_title")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_title)
        self.horizontalLayout_5.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_title)
        self.pushButton_2.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/icon/coffee.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.label = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.close_account = QtWidgets.QPushButton(self.frame_title)
        self.close_account.setMinimumSize(QtCore.QSize(30, 30))
        self.close_account.setMaximumSize(QtCore.QSize(30, 30))
        self.close_account.setText("")
        self.close_account.setObjectName("close_account")
        self.horizontalLayout_5.addWidget(self.close_account)
        self.verticalLayout_2.addWidget(self.frame_title)
        self.frame_dialog_file = QtWidgets.QFrame(self.frame_main)
        self.frame_dialog_file.setStyleSheet("")
        self.frame_dialog_file.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_dialog_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_dialog_file.setObjectName("frame_dialog_file")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_dialog_file)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_file = QtWidgets.QLineEdit(self.frame_dialog_file)
        self.lineEdit_file.setMinimumSize(QtCore.QSize(220, 40))
        self.lineEdit_file.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_file.setStyleSheet("")
        self.lineEdit_file.setObjectName("lineEdit_file")
        self.verticalLayout.addWidget(self.lineEdit_file)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_createfile = QtWidgets.QPushButton(self.frame_dialog_file)
        self.pushButton_createfile.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_createfile.setFont(font)
        self.pushButton_createfile.setStyleSheet("QPushButton {\n"
"    \n"
"    border-radius: 5px;    \n"
"    color : rgb(255,255,255);\n"
"    \n"
"    background-color: rgb(75, 104, 133);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"    padding-right:3px;\n"
"}")
        self.pushButton_createfile.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_createfile.setObjectName("pushButton_createfile")
        self.horizontalLayout_2.addWidget(self.pushButton_createfile)
        self.pushButton_importaccount = QtWidgets.QPushButton(self.frame_dialog_file)
        self.pushButton_importaccount.setMinimumSize(QtCore.QSize(185, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_importaccount.setFont(font)
        self.pushButton_importaccount.setStyleSheet("QPushButton {\n"
"    \n"
"    border-radius: 5px;    \n"
"    color : rgb(255,255,255);\n"
"    \n"
"    background-color: rgb(75, 104, 133);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"    padding-right:3px;\n"
"}")
        self.pushButton_importaccount.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_importaccount.setObjectName("pushButton_importaccount")
        self.horizontalLayout_2.addWidget(self.pushButton_importaccount)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.frame_dialog_file)
        self.horizontalLayout.addWidget(self.frame_main)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Tạo file"))
        self.label.setText(_translate("Dialog", "Tạo file "))
        self.lineEdit_file.setPlaceholderText(_translate("Dialog", "Nhập tên thư mục..."))
        self.pushButton_createfile.setText(_translate("Dialog", "Tạo File"))
        self.pushButton_createfile.setShortcut(_translate("Dialog", "Return"))
        self.pushButton_importaccount.setText(_translate("Dialog", "Nhập tài khoản"))
        self.pushButton_importaccount.setShortcut(_translate("Dialog", "Ctrl+T"))
import files_rc
