# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\app\widget\ui\view_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(389, 208)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_view = QtWidgets.QFrame(Dialog)
        self.frame_view.setStyleSheet("border-radius:5px;")
        self.frame_view.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_view.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_view.setObjectName("frame_view")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_view)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_title = QtWidgets.QFrame(self.frame_view)
        self.frame_title.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_title.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_title.setObjectName("frame_title")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_title)
        self.horizontalLayout_5.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_title)
        self.pushButton_2.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/icon/coffee.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.label = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.close_account = QtWidgets.QPushButton(self.frame_title)
        self.close_account.setMinimumSize(QtCore.QSize(30, 30))
        self.close_account.setMaximumSize(QtCore.QSize(30, 30))
        self.close_account.setText("")
        self.close_account.setObjectName("close_account")
        self.horizontalLayout_5.addWidget(self.close_account)
        self.verticalLayout.addWidget(self.frame_title)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(10, -1, 10, 0)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self._2fa = QtWidgets.QCheckBox(self.frame_view)
        self._2fa.setChecked(False)
        self._2fa.setObjectName("_2fa")
        self.gridLayout.addWidget(self._2fa, 1, 1, 1, 1)
        self.uid = QtWidgets.QCheckBox(self.frame_view)
        self.uid.setChecked(False)
        self.uid.setObjectName("uid")
        self.gridLayout.addWidget(self.uid, 0, 2, 1, 1)
        self.comment = QtWidgets.QCheckBox(self.frame_view)
        self.comment.setChecked(False)
        self.comment.setObjectName("comment")
        self.gridLayout.addWidget(self.comment, 2, 0, 1, 1)
        self.passw = QtWidgets.QCheckBox(self.frame_view)
        self.passw.setChecked(False)
        self.passw.setAutoRepeatDelay(100)
        self.passw.setObjectName("passw")
        self.gridLayout.addWidget(self.passw, 1, 0, 1, 1)
        self.name = QtWidgets.QCheckBox(self.frame_view)
        self.name.setChecked(False)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 1, 1, 1)
        self.img = QtWidgets.QCheckBox(self.frame_view)
        self.img.setChecked(False)
        self.img.setObjectName("img")
        self.gridLayout.addWidget(self.img, 2, 1, 1, 1)
        self.cookie = QtWidgets.QCheckBox(self.frame_view)
        self.cookie.setChecked(False)
        self.cookie.setObjectName("cookie")
        self.gridLayout.addWidget(self.cookie, 1, 2, 1, 1)
        self.stt = QtWidgets.QCheckBox(self.frame_view)
        self.stt.setChecked(False)
        self.stt.setObjectName("stt")
        self.gridLayout.addWidget(self.stt, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame_view)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    \n"
"    border-radius: 5px;    \n"
"    color : rgb(255,255,255);\n"
"    \n"
"    background-color: rgb(75, 104, 133);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"    padding-right:3px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 3)
        self.status = QtWidgets.QCheckBox(self.frame_view)
        self.status.setChecked(False)
        self.status.setObjectName("status")
        self.gridLayout.addWidget(self.status, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout.addWidget(self.frame_view)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Cài đặt hiển thị"))
        self.label.setText(_translate("Dialog", "Cài đặt chế độ hiển thị"))
        self._2fa.setText(_translate("Dialog", "Mã bảo mật"))
        self.uid.setText(_translate("Dialog", "Uid"))
        self.comment.setText(_translate("Dialog", "Comment"))
        self.passw.setText(_translate("Dialog", "Mật khẩu"))
        self.name.setText(_translate("Dialog", "Tên"))
        self.img.setText(_translate("Dialog", "Ảnh"))
        self.cookie.setText(_translate("Dialog", "Cookie"))
        self.stt.setText(_translate("Dialog", "Số thứ tự"))
        self.pushButton.setText(_translate("Dialog", "Lưu "))
        self.status.setText(_translate("Dialog", "Trạng thái"))
import files_rc
